### PR TITLE
Template postgresql.conf, add additional options

### PR DESCRIPTION
**Pull request by manics**
**Breaking change**

This makes `postgresql.conf` a templated file instead of using `lineinfile` to modify the version installed by the distribution package, and adds a variable `postgresql_server_conf` so additional options can be defined.

Originally this was implemented using `lineinfile` only: 7a1eb6e957e6face46e549a39c4d9a44e5483cd4.

This provided full backwards compatibility but meant the config could not be guaranteed, since removing an option from the `postgresql_server_conf` dict would not remove it from an existing `postgresql.conf`. Making it a template is more reliable.

In practice this should be non-breaking for most existing 9.6 server installations, since the template is based on `/var/lib/pgsql/9.6/data/postgresql.conf` from `postgresql96-server-9.6.3-1PGDG.rhel7.x86_64`: 43221253efd1fd406cb2956414686ebb6716d04c
though will result in a restart due to re-ordering and whitespace changes.

Additionally the variable `postgresql_install_extensions` will install the `-contrib` package.

Tag: `3.0.0-m1`, https://github.com/openmicroscopy/ansible-role-postgresql/pull/7 is another breaking change which can go into `3.0.0`

### CODE REVIEW

**Comment by joshmoore** [comment]
Updated the description to point to #7 (assuming that's what you meant).

If we're moving into breaking version land, should we review requirements files to see if any need to be pinned to 2.x?

**Comment by joshmoore** [comment]
Otherwise, probably my biggest concern is how to detect when an upstream update to the template is needed.

**Comment by manics** [comment]
I'd expect future 9.X versions of postgres to work with an unchanged config file.

**Comment by joshmoore** [comment]
> I'd expect future 9.X versions of postgres to work with an unchanged config file.

Took a look at the PG git. :+1: Capping at below 10 then sounds sensible.

> If we're moving into breaking version land, should we review requirements files to see if any need to be pinned to 2.x?

Any thoughts before merging?

**Comment by manics** [comment]
>> If we're moving into breaking version land, should we review requirements files to see if any need to be pinned to 2.x?
>
> Any thoughts before merging?

The current config is fairly similar to a standard PG 9.6 config, and it passes the molecule tests on all supported PG versions, so I'd expect this to work. Therefore the main questions are:
- have you modified the postgres.conf outside of this role (I'm not aware of any of our playbooks that do this, but if you want to be 100% sure you'd have to review all playbooks task-by-task).
- are you happy with a postgres restart due to re-ordering and whitespace changes? If you're not then you shouldn't update (but this applies to all roles).

**Comment by manics** [comment]
In addition for a critical piece of infrastructure like PG I think you should **always** pin a specific version.

**Comment by joshmoore** [comment]
Waiting on:

 * https://github.com/openmicroscopy/infrastructure/pull/298
 * https://github.com/ome/ansible-examples-omero/pull/1

**Comment by joshmoore** [comment]
Merging & tagging.

**Pull request merged**
