### PR TITLE
Add postgres 9.5 and 9.6

### PR DESCRIPTION
**Pull request by manics**
Adds `9.5` and `9.6`, the default remains at `9.4`.
Also contains a minor change to ensure the `postgresql.conf` backup file is owned by `postgres` instead of `root`, to avoid a idempotence warning which occurs in the IDR playbooks.

Tag: ~non-breaking addition so `1.1.0`~ `9.3` was removed so `2.0.0`

### CODE REVIEW

**Comment by jburel** [comment]
not directly related to this PR but I started this morning one devspace with 9.5 and one with 9.6 
cf. https://trello.com/c/pqPzTMPY/235-omero-may-break-with-postgresql-9-6

**Comment by jburel** [comment]
The test file name should be unified:
 * ``test_postgres_95_96.py`` and ``test_postgresql-94.py``
use ``_`` in both and ``postgresql``
 * 9.3 version could be removed.

Tested with both docker and vagrant

**Comment by manics** [comment]
Updated as requested

**Comment by jburel** [comment]
Thanks for making the change
Looks good ready to merge

**Pull request merged**
