### PR TITLE
Restrict access

### PR DESCRIPTION
**Pull request by manics**
**Breaking change**

This refactors the creation of databases and users, and provides the basis for implementing more restrictive permissions outside of this role. The variable `postgresql_users_databases` is replaced by `postgresql_databases` and `postgresql_users`.

As described in the README most privileges can only be set after a schema has been populated. This role simply removes most default privileges if `restrict: True` is set on a database (the default privileges associated with the postgres `PUBLIC` role are surprisingly open)- see `tests/test_privileges.py` for examples of what users can do. The default for `restrict` is `False` so the default privileges will be the same as before.

Note the molecule playbook goes beyond a minimal test since it includes a `postgresql_privs` task that is run after this role has been deployed. The benefit is `tests/test_privileges.py` can provide a clearer example of the intention of this PR (and also the limitations of this role), the obvious disadvantage is that it's testing something that isn't part of this role. Keep or remove?

Closes https://github.com/openmicroscopy/ansible-role-postgresql/issues/5

(Rebased on top of #6)

### CODE REVIEW

**Comment by joshmoore** [comment]
* Perhaps fail if `postgresql_users_databases` is set so users know to upgrade
 * The compromise of `restrict: True` seems fine, though I'd hope we could find some library, role, etc. to encapsulate all the logic starting at https://github.com/openmicroscopy/ansible-role-postgresql/pull/7/files#diff-e009a2f628f6296f6af929d169317e00R36
 * "Keep or remove?" I'd keep unless as with public user we're moving it to some other targeted repo.

**Comment by manics** [comment]
Updated to fail with `postgresql_users_databases`. Also fixed a bug and added a test for when `postgresql_install_server: False`

**Comment by joshmoore** [comment]
Changes look good to me. Tag as 3.0.0-m2?

**Comment by manics** [comment]
Yes

**Pull request merged**
