### PR TITLE
Update to use Rockylinux 9 and Ubuntu 22.04

### PR DESCRIPTION
**Pull request by khaledk2**
It failed for Rocky Linux 9 with this error
https://github.com/khaledk2/ansible-role-postgresql/actions/runs/6275413708/job/17042853222#step:5:192
I think it uses [ome.postgresql_client](https://github.com/ome/ansible-role-postgresql-client) and this should be resolved after merging  [PR 8](https://github.com/ome/ansible-role-postgresql-client/pull/8) for postgresql_client

### CODE REVIEW

**Comment by sbesson** [comment]
> I think it uses [ome.postgresql_client](https://github.com/ome/ansible-role-postgresql-client) and this should be resolved after merging https://github.com/ome/ansible-role-postgresql-client/pull/8 for postgresql_client

I agree, we are starting to hit the roadblock discussed last Tuesday i.e. the problem of making significant changes like new platform support across  multiple interdependent roles. Fundamentally, one of the issues here is that the Ansible Galaxy metadata is used in an informative way and Ansible roles lack a proper dependency mechanism e.g. allowing to specify min/max versions of the dependencies - see https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#using-role-dependencies

One possible resolution as you suggested is to start integrating and releasing new versions with Rocky Linux 9 / Ubuntu 22.04 support. The primary downside are that all downstream roles will start failing the scheduled Molecule CI builds as the latest roles will be incompatible with CentOS 7.

**Comment by khaledk2** [comment]
I have pointed out the `postgresql_client` to the  GitHub `postgresql_client` [PR 8](https://github.com/ome/ansible-role-postgresql-client/pull/8).  It did not pass but I think this change has fixed the issue related to the need to use the updated `postgresql_client`.  cc  @pwalczysko @jburel

**Comment by khaledk2** [comment]
I have checked the issue which I mentioned in my last comment; it has this error `invalid locale name "en_US.UTF-8"` when running  to run `ninitdb` in the Rocky Linux, I have added a [task  ](https://github.com/ome/ansible-role-postgresql/pull/34/files#:~:text=%2D%20name%3A%20get%20langpack%20for%20en)to redhat.yml to install `glibc-langpack-en `which solved the issue and it passed now!

**Comment by jburel** [comment]
@khaledk2 This is similar to what I had to do for devspace 
see https://github.com/jburel/devslave-c7-docker/blob/master/Dockerfile#L10

**Pull request merged**
